### ISSUE TITLE
api.err.LoginRequired

### ISSUE THREAD

**Issue by backisen** [rootnegativ1/unifi-wifi#19]
I get this error when adding unifi-wifi to configuration.yaml:

```
Logger: custom_components.unifi_wifi.coordinator
Source: helpers/update_coordinator.py:353
Integration: Unifi Wifi (documentation, issues)
First occurred: 10:52:00 (1 occurrences)
Last logged: 10:52:00

Authentication failed while fetching klubben319 data: {'meta': {'rc': 'error', 'msg': 'api.err.LoginRequired'}, 'data': []}
```

unifi-wifi installed via HACS. Running latest stable version of HAOS and Home Assistant. 

configuration.yaml:
```
unifi_wifi:
  - name: klubben319
    host: wifi.klubben319.se
    port: 443
    username: REDACTED
    password: REDACTED
```

The unifi controller can be accessed at the adress stated in host. I have double and triple checked username and password.

**Comment by rootnegativ1** [comment]
When I entered your host:port in a browser the login screen was available. That login screen indicates your controller is not using UniFi OS. If this is the case, try including ```unifi_os: false``` in your YAML.

Is the controller supposed to be widely accessible on the internet?

**Comment by backisen** [comment]
> When I entered your host:port in a browser the login screen was available. That login screen indicates your controller is not using UniFi OS. If this is the case, try including `unifi_os: false` in your YAML.
> 
> Is the controller supposed to be widely accessible on the internet?

Thanks, that was the problem.

Running the services doesn't change anything. Nothing to be found in homeassistant logs. Is there relevant logs somewhere else?

```
service: unifi_wifi.random_password
data:
  target:
    entity_id: image.klubben319_guest_qr_code
  method: xkcd
```
