### ISSUE TITLE
Add option for black and white QR codes

### ISSUE THREAD

**Issue by pppaapp** [rootnegativ1/unifi-wifi#55]
hello

The current QR codes are gray

Please add an option to generate QR codes in black and white for better clarity

Thank you!

![이미지](https://github.com/user-attachments/assets/9de51c89-2716-4944-8fab-9f8769a5eccb)

**Comment by rootnegativ1** [comment]
Do you have ```fill_color``` and ```back_color``` defined in your YAML config? If so, try removing them.

```yaml
unifi_wifi:
  - name: myhouse
   # other options
    monitored_ssids:
      # this image will be gray like the screenshot you attached
      - name: grayLAN
        fill_color: '#aaaaaa'
        back_color: '#bbbbbb'

      # this image will be black and white since those are the default colors
      - name: blackNwhiteLAN 
```
